name: guppy-gpu
version: '5.0.16+b9fcd7b5b'

summary: experimental guppy gpu basecaller snap
description: |
  guppy is a GPU based basecaller for nanopore data
base: core20
grade: stable
confinement: strict
#icon: snap/gui/icon.png

apps:
  guppy:
    command: opt/ont/guppy/bin/guppy_basecaller
    plugs:
      - home
      - network
      - network-bind
    
parts:
  guppy:
    plugin: nil
    stage-packages:
      - minknow-core-minion-nc 
      - ont-kingfisher-ui-minion
      - ont-bream4-minion
      - ont-configuration-customer-minion
      - ont-jwt-auth
      - ont-vbz-hdf-plugin
      - ont-guppy   
    after: [ont-repo]
    
  ont-repo:
    plugin: nil
    build-packages:    
      - wget
    override-pull: |
          wget -O- https://mirror.oxfordnanoportal.com/apt/ont-repo.pub | sudo apt-key add -
          echo "deb http://mirror.oxfordnanoportal.com/apt focal-stable non-free" | sudo tee /etc/apt/sources.list.d/nanoporetech.sources.list
          apt -y update